### ISSUE TITLE
Images in /screenshots folders

### ISSUE THREAD

**Issue by w3ichen** [eliabntt/gazebo_resources#1]
@eliabntt just a heads up that you might have accidentally uploaded some personal photos int the screenshots folder, such as 
https://github.com/eliabntt/gazebo_resources/blob/master/screenshots/DeskPortraitA_01.jpg.
That is DeskPortrait[A-D] and Portrait[A-E]

**Comment by eliabntt** [comment]
I believe I only did some mixing of folders 

E.g. portrait is here https://github.com/eliabntt/gazebo_resources/blob/8c4df5ebec9f2cbdea63b0215b01c156d8b7bbe5/models/aws_robomaker_residential_PortraitA_01/meshes/aws_PortraitA_01_visual.DAE#L9

Those are just textures of assets in the worlds
